apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags-config
  namespace: default
  labels:
    app: frontend
    managed-by: storedog
    purpose: feature-flags
    environment: development
    tier: application
data:
  featureFlags.config.json: |
    [
      {
        "id": "1",
        "name": "dbm",
        "active": false
      },
      {
        "id": "2",
        "name": "error-tracking",
        "active": false
      },
      {
        "id": "3",
        "name": "api-errors",
        "active": false
      },
      {
        "id": "4",
        "name": "product-card-frustration",
        "active": false
      }
    ] 